name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Node.js Version 8.x
        # Continue to test against this older version to make it easier to test
        # Bertha regressions since the upgrade to the new Google APIs (Bertha was pinned to version 8 too)
        # Note we still use Jest 25 for this reason.
        node-version: [8.x, 12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
